use seshat::bench::*;
use std::path::PathBuf;

fn main() {
    let cm = Some("gpt-5".to_string());
    let lm = Some("claude-sonnet-4-6".to_string());
    let om = Some("seshat-commit".to_string());

    let report = AgentBenchReport {
        iterations: 3,
        agents: vec!["codex".into(), "claude".into(), "ollama".into()],
        agent_selection: AgentSelection::Explicit,
        fixtures: vec!["rust".into(), "python".into(), "typescript".into()],
        temp_root: Some(PathBuf::from("/tmp/seshat-bench-demo")),
        summaries: vec![
            AgentBenchSummary {
                fixture: "rust".into(),
                agent: "codex".into(),
                model: cm.clone(),
                total: 3,
                success: 3,
                conventional_valid: 3,
                avg_ms: 3210.0,
                min_ms: 3050.0,
                p95_ms: 3450.0,
                max_ms: 3450.0,
            },
            AgentBenchSummary {
                fixture: "rust".into(),
                agent: "claude".into(),
                model: lm.clone(),
                total: 3,
                success: 3,
                conventional_valid: 3,
                avg_ms: 4200.0,
                min_ms: 4180.0,
                p95_ms: 4310.0,
                max_ms: 4310.0,
            },
            AgentBenchSummary {
                fixture: "rust".into(),
                agent: "ollama".into(),
                model: om.clone(),
                total: 3,
                success: 3,
                conventional_valid: 2,
                avg_ms: 1180.0,
                min_ms: 1100.0,
                p95_ms: 1340.0,
                max_ms: 1340.0,
            },
            AgentBenchSummary {
                fixture: "python".into(),
                agent: "codex".into(),
                model: cm.clone(),
                total: 3,
                success: 3,
                conventional_valid: 2,
                avg_ms: 3110.0,
                min_ms: 2950.0,
                p95_ms: 3300.0,
                max_ms: 3300.0,
            },
            AgentBenchSummary {
                fixture: "python".into(),
                agent: "claude".into(),
                model: lm.clone(),
                total: 3,
                success: 3,
                conventional_valid: 3,
                avg_ms: 4400.0,
                min_ms: 4200.0,
                p95_ms: 4600.0,
                max_ms: 4600.0,
            },
            AgentBenchSummary {
                fixture: "python".into(),
                agent: "ollama".into(),
                model: om.clone(),
                total: 3,
                success: 3,
                conventional_valid: 1,
                avg_ms: 1240.0,
                min_ms: 1180.0,
                p95_ms: 1400.0,
                max_ms: 1400.0,
            },
            AgentBenchSummary {
                fixture: "typescript".into(),
                agent: "codex".into(),
                model: cm.clone(),
                total: 3,
                success: 3,
                conventional_valid: 3,
                avg_ms: 3050.0,
                min_ms: 2900.0,
                p95_ms: 3200.0,
                max_ms: 3200.0,
            },
            AgentBenchSummary {
                fixture: "typescript".into(),
                agent: "claude".into(),
                model: lm.clone(),
                total: 3,
                success: 2,
                conventional_valid: 2,
                avg_ms: 4150.0,
                min_ms: 4000.0,
                p95_ms: 4280.0,
                max_ms: 4280.0,
            },
            AgentBenchSummary {
                fixture: "typescript".into(),
                agent: "ollama".into(),
                model: om.clone(),
                total: 3,
                success: 3,
                conventional_valid: 3,
                avg_ms: 1290.0,
                min_ms: 1200.0,
                p95_ms: 1410.0,
                max_ms: 1410.0,
            },
        ],
        overall: vec![
            AgentBenchOverallSummary {
                agent: "claude".into(),
                model: lm.clone(),
                total: 9,
                success: 8,
                conventional_valid: 8,
                avg_ms: 4220.0,
                min_ms: 4000.0,
                p95_ms: 4600.0,
                max_ms: 4600.0,
                fixtures_won: 2,
            },
            AgentBenchOverallSummary {
                agent: "codex".into(),
                model: cm.clone(),
                total: 9,
                success: 9,
                conventional_valid: 8,
                avg_ms: 3120.0,
                min_ms: 2900.0,
                p95_ms: 3450.0,
                max_ms: 3450.0,
                fixtures_won: 1,
            },
            AgentBenchOverallSummary {
                agent: "ollama".into(),
                model: om.clone(),
                total: 9,
                success: 9,
                conventional_valid: 6,
                avg_ms: 1240.0,
                min_ms: 1100.0,
                p95_ms: 1410.0,
                max_ms: 1410.0,
                fixtures_won: 0,
            },
        ],
        samples: vec![
            AgentBenchSample {
                fixture: "rust".into(),
                agent: "codex".into(),
                model: cm.clone(),
                iteration: 1,
                duration_ms: 3120.0,
                success: true,
                conventional_valid: true,
                message: Some("feat: adicionar testes para função calculate_total".into()),
                error: None,
                diff: String::new(),
            },
            AgentBenchSample {
                fixture: "rust".into(),
                agent: "claude".into(),
                model: lm.clone(),
                iteration: 1,
                duration_ms: 4250.0,
                success: true,
                conventional_valid: true,
                message: Some("test(lib): cobrir calculate_total com testes unitários".into()),
                error: None,
                diff: String::new(),
            },
            AgentBenchSample {
                fixture: "rust".into(),
                agent: "ollama".into(),
                model: om.clone(),
                iteration: 1,
                duration_ms: 1180.0,
                success: true,
                conventional_valid: true,
                message: Some("feat(lib): adicionar testes unitários para calculate_total".into()),
                error: None,
                diff: String::new(),
            },
            AgentBenchSample {
                fixture: "python".into(),
                agent: "codex".into(),
                model: cm.clone(),
                iteration: 1,
                duration_ms: 3110.0,
                success: true,
                conventional_valid: true,
                message: Some("feat: adicionar testes para módulo de cálculo".into()),
                error: None,
                diff: String::new(),
            },
            AgentBenchSample {
                fixture: "python".into(),
                agent: "claude".into(),
                model: lm.clone(),
                iteration: 1,
                duration_ms: 4400.0,
                success: true,
                conventional_valid: true,
                message: Some("test: adicionar suite de testes para função total".into()),
                error: None,
                diff: String::new(),
            },
            AgentBenchSample {
                fixture: "python".into(),
                agent: "ollama".into(),
                model: om.clone(),
                iteration: 1,
                duration_ms: 1240.0,
                success: false,
                conventional_valid: false,
                message: None,
                error: Some("connection refused".into()),
                diff: String::new(),
            },
        ],
        show_samples: 1,
        override_notes: Vec::new(),
    };
    print_report(&report, ReportLanguage::Portuguese);
}
